#!/bin/bash

docker run -p 8501:8501 -e GOOGLE_API_KEY=$GOOGLE_API_KEY \
-e LANGSMITH_API_KEY=$LANGSMITH_API_KEY \
-e LANGSMITH_WORKSPACE_ID=$LANGSMITH_WORKSPACE_ID \
-e LANGSMITH_ENDPOINT=$LANGSMITH_ENDPOINT \
-e LANGSMITH_PROJECT=$LANGSMITH_PROJECT \
-e LANGSMITH_TRACING=$LANGSMITH_TRACING \
-e LANGCHAIN_CALLBACKS_BACKGROUND=$LANGCHAIN_CALLBACKS_BACKGROUND \
jackypck/earning_call_agent